### ISSUE TITLE
Document the required EdgeDB generator params

### ISSUE THREAD

**Issue by jere-co** [Zainrax/authjs-edgedb#1]
At least with default generator params, trying to reference the `e.auth.User` produces an error `'auth' does not exist on type'. 

However, simply `e.User` does exist. Is there an EdgeDB generator param that allows such usage?

**Comment by Zainrax** [comment]
It's likely because you're missing the "module auth" in default.esdl. If you want it in your default module just remove the auth like you did.

**Comment by jere-co** [comment]
Actually had it there, but I didn't start from a fresh DB and had those originally inside the default module, which seemed to stick with the db migration. All good after starting fresh.
